<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DirectShowLib.Standard" Version="2.1.0" />
    <PackageVersion Include="Emgu.CV" Version="4.5.5.4823" />
    <PackageVersion Include="Emgu.CV.runtime.windows" Version="4.5.5.4823" />
    <PackageVersion Include="Emgu.CV.UI" Version="4.5.5.4823" />
    <PackageVersion Include="font-awesome" Version="4.7.0" />
    <PackageVersion Include="HelixToolkit.Core.Wpf" Version="2.22.0" />
    <PackageVersion Include="LagoVista.CloudStorage" Version="6.0.1" />
    <PackageVersion Include="LagoVista.Core" Version="6.0.10" />
    <PackageVersion Include="LagoVista.Core.Configuration" Version="6.0.10" />
    <PackageVersion Include="LagoVista.Core.TestBase" Version="6.0.10" />
    <PackageVersion Include="LagoVista.IoT.Web.Common" Version="6.0.1" />
    <PackageVersion Include="LagoVista.MediaServices" Version="6.0.0" />
    <PackageVersion Include="LagoVista.PDFServices" Version="6.0.10" />
    <PackageVersion Include="LagoVista.UserAdmin" Version="6.0.1" />
    <PackageVersion Include="LagoVista.UserAdmin.Models" Version="6.0.1" />
    <PackageVersion Include="Meziantou.WpfFontAwesome" Version="5.15.4" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="QRCoder" Version="1.7.0" />
    <PackageVersion Include="SharpDX.XInput" Version="4.2.0" />
    <PackageVersion Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>
</Project>
