<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>0.8</VersionPrefix>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.CloudStorage" />
    <PackageReference Include="LagoVista.Core.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LagoVista.Manufacturing.Models\LagoVista.Manufacturing.Models.csproj" />
    <ProjectReference Include="..\LagoVista.Manufacturing\LagoVista.Manufacturing.csproj" />
  </ItemGroup>
</Project>
